### YamlMime:Landing
title: Azure Arc 사용 Kubernetes(미리 보기)
summary: Azure Arc로 Kubernetes 클러스터를 관리하는 방법 알아보기
metadata:
  title: Azure Arc를 지원하는 Kubernetes
  description: Azure에서 온-프레미스 머신을 관리하는 방법에 대해 알아보기
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 02/15/2021
  ms.author: shasb
  ms.openlocfilehash: 97343e8c23e202e70ec30bb0a522105889ea08b3
  ms.sourcegitcommit: de98cb7b98eaab1b92aa6a378436d9d513494404
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 02/17/2021
  ms.locfileid: "100560236"
landingContent:
- title: Azure Arc를 사용하여 Kubernetes 클러스터를 Azure에 연결
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc를 지원하는 Kubernetes란 무엇인가요?
      url: overview.md
  - linkListType: concept
    links:
    - text: 에이전트 아키텍처
      url: conceptual-agent-architecture.md
    - text: 구성 및 GitOps
      url: conceptual-configurations.md
    - text: 질문과 대답
      url: faq.md
- title: 시작
  linkLists:
  - linkListType: quickstart
    links:
    - text: 클러스터 연결
      url: connect-cluster.md
- title: 클러스터 구성, 제어 및 모니터링
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: GitOps를 사용하여 구성 배포
      url: use-gitops-connected-cluster.md
    - text: GitOps를 사용하여 Helm 차트 배포
      url: use-gitops-with-helm.md
    - text: Azure Policy를 사용하여 GitOps 적용
      url: use-azure-policy.md
    - text: Azure IoT 에지 워크로드 배포
      url: deploy-azure-iot-edge-workloads.md
- title: 개념 증명
  linkLists:
  - linkListType: sample
    links:
    - text: 빠른 시작
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: 참조 아키텍처
  linkLists:
  - linkListType: architecture
    links:
    - text: 하이브리드 Kubernetes 클러스터의 배포 및 구성 관리
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
